### ISSUE TITLE
NotSerializableException when reading from Kafka using KafkaColumnType.AvroSchemaRegistry

### ISSUE THREAD

**Issue by MarkusRothSBB** [smart-data-lake/smart-data-lake#198]
When reading from Kafka-Topics, KafkaColumnType.Binary and KafkaColumnType.String work fine. When I use KafkaColumnType.AvroSchemaRegistry, I get a NotSerializableException with the following serialization stack:
```
        - object not serializable (class: org.apache.avro.Schema$RecordSchema, value: {"type":"record","name":"User","namespace":"ch.sbb.kafka.avro.model","fields":[{"name":"id","type":{"type":"string","avro.java.string":"String"}},{"name":"firstName","type":{"type":"string","avro.java.string":"String"}},{"name":"lastName","type":{"type":"string","avro.java.string":"String"}},{"name":"email","type":{"type":"string","avro.java.string":"String"},"default":""},{"name":"attr1","type":{"type":"string","avro.java.string":"String"},"default":""}]})
        - field (class: scala.Tuple2, name: _2, type: class java.lang.Object)
        - object (class scala.Tuple2, (15,{"type":"record","name":"User","namespace":"ch.sbb.kafka.avro.model","fields":[{"name":"id","type":{"type":"string","avro.java.string":"String"}},{"name":"firstName","type":{"type":"string","avro.java.string":"String"}},{"name":"lastName","type":{"type":"string","avro.java.string":"String"}},{"name":"email","type":{"type":"string","avro.java.string":"String"},"default":""},{"name":"attr1","type":{"type":"string","avro.java.string":"String"},"default":""}]}))
        - field (class: org.apache.spark.sql.avro.confluent.ConfluentAvroDataToCatalyst, name: x$1, type: class scala.Tuple2)
        - object (class org.apache.spark.sql.avro.confluent.ConfluentAvroDataToCatalyst, from_avro(input[1, binary, true], eap-demo.test.avro-value, org.apache.spark.sql.avro.confluent.ConfluentClient@70537a2d))
        - element of array (index: 1)
        - array (class [Ljava.lang.Object;, size 2)
        - element of array (index: 1)
        - array (class [Ljava.lang.Object;, size 3)
        - field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
        - object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class org.apache.spark.sql.execution.WholeStageCodegenExec, functionalInterfaceMethod=scala/Function2.apply:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeStatic org/apache/spark/sql/execution/WholeStageCodegenExec.$anonfun$doExecute$4$adapted:(Lorg/apache/spark/sql/catalyst/expressions/codegen/CodeAndComment;[Ljava/lang/Object;Lorg/apache/spark/sql/execution/metric/SQLMetric;Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, instantiatedMethodType=(Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, numCaptured=3])
        - writeReplace data (class: java.lang.invoke.SerializedLambda)
        - object (class org.apache.spark.sql.execution.WholeStageCodegenExec$$Lambda$2519/1862323076, org.apache.spark.sql.execution.WholeStageCodegenExec$$Lambda$2519/1862323076@12e1060e)
        at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:41)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
        at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:101)
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:413)
        ... 74 more
```

The field that can't be serialized seems to be tgtSchema in the case class ConfluentAvroDataToCatalyst.

confluentHelper on KafkaConnection is @transient lazy, which I think should prevent this from happening. But the exception still occurs.

Maybe calling from_confluent_avro leads to ConfluentAvroDataToCatalyst being part of the closure to be serialized even if confuentHelper is transient? I'm not sure what is going on here to be honest.

To reproduce the bug, a Confluent Schema Registry is required. I have this configuration within the SBB network:

```
connections = {
  kafka = {
    type = KafkaConnection
    brokers = "<kafka-broker-url>"
    schema-registry = "<schema-registry-url>"
    auth-mode = {
      type = SSLCertsAuthMode
      keystore-path = keystore.p12
      keystore-pass-variable = "CLEAR#test"
      keystore-type = PKCS12
      truststore-path = truststore.p12
      truststore-pass-variable = "CLEAR#test"
      truststore-type = PKCS12
    }
    datasource-options = {
      groupidprefix = "projectname."
    }
  }
}

dataObjects = {
  kafka-avro = {
    type = KafkaTopicDataObject
    topic-name = projectname.test.avro
    connection-id = kafka
    value-type = AvroSchemaRegistry
  }
}
```

**Comment by MarkusRothSBB** [comment]
Maybe the problem is that SBB is using Confluent Platform 5.5.1 (Kafka 2.5.0), while SDL is using Kafka 2.4.1?

**Comment by zzeekk** [comment]
Hi @MarkusRothSBB , the problem seems to be inside ConfluentAvroDataToCatalyst, which is in spark-extensions of SDL:
https://github.com/smart-data-lake/spark-extensions/blob/develop/src/main/scala/org/apache/spark/sql/avro/confluent/ConfluentAvroDataToCatalyst.scala

I have this code working with schema registry, but not distributed... so there might be an issue with serialization. Does it work for you in non-distributed mode (locally from IntelliJ or on gateway in spark local mode)?

If you look at ConfluentAvroToCatalyst, most fields are already @transient. We could try to make dataType @transient, though it doesn't keep a reference to tgtSchema in my opinion...

**Comment by zzeekk** [comment]
Hi @MarkusRothSBB , I found an optimization in ConfluentAvroDataToCatalyst, to not store the avro schema in an instance variable. If you want you can try building spark-extensions branch bugfix/198-avro-schema-not-serializable (https://github.com/smart-data-lake/spark-extensions/tree/bugfix/198-avro-schema-not-serializable), then update spark-extensions version in sdl-parent to 1.0.1-SNAPSHOT, then build SDL and try again?
