### ISSUE TITLE
Add action name to thread name

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#200]
**Is your feature request related to a problem? Please describe.**
When running multiple Actions in parallel, the thread name must be used to find the logs for a specific Action. For now the thread name is a number like "dag-1-123". The same thread can be used for other Actions later in the feed. The situation could be improved by adding the Action name to the thread.

**Describe the solution you'd like**
In DAG before starting a phase for an Action, change the name of the thread:
Thread.currentThread.setName("dag-<phase>-<actionName>")
If phase is finished, revert the name.
This can be implemented in Action.prepare/init/preExec/postExec methods.

**Additional context**
Note that DAG execution with Monix assigns a thread to the execution of a Task. It can be therefore be assumed that a thread is not used to execute different Actions at the same time.

**Comment by zzeekk** [comment]
Bonus: simplify final exception message when SDL fails. Remove stacktrace from toplevel exception as it is specific to the DAG execution:
```
Exception in thread "main" io.smartdatalake.workflow.TaskFailedException: abc
	at io.smartdatalake.workflow.TaskFailedException$.apply(DAGException.scala:36)
	at io.smartdatalake.workflow.DAG.computeNodeOperationResult(DAG.scala:168)
	at io.smartdatalake.workflow.DAG.$anonfun$buildTaskGraph$2(DAG.scala:130)
	at monix.eval.Task$Map.apply(Task.scala:4541)
	at monix.eval.Task$Map.apply(Task.scala:4537)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:170)
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
	at monix.eval.internal.TaskRestartCallback$$anon$1.run(TaskRestartCallback.scala:118)
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
	at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:132)
	at monix.execution.internal.Trampoline.execute(Trampoline.scala:40)
	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:57)
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
	at monix.execution.schedulers.ExecutorScheduler.execute(ExecutorScheduler.scala:35)
	at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:72)
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:165)
	at monix.eval.internal.TaskMemoize$Register.$anonfun$registerListener$1(TaskMemoize.scala:129)
	at monix.eval.internal.TaskMemoize$Register.$anonfun$registerListener$1$adapted(TaskMemoize.scala:125)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.smartdatalake.workflow.action.MetricsCheckFailed: (Action~abc) metrics check failed: Metric(dataObjectId=abc key=Some(records_written) value=Some(30)) matched expression "key = 'records_written' and value > 0
	at io.smartdatalake.workflow.action.Action.$anonfun$evaluateMetricsFailCondition$5(Action.scala:176)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at io.smartdatalake.workflow.action.Action.evaluateMetricsFailCondition(Action.scala:176)
	at io.smartdatalake.workflow.action.Action.$anonfun$postExec$1(Action.scala:158)
	at io.smartdatalake.workflow.action.Action.$anonfun$postExec$1$adapted(Action.scala:158)
	at scala.Option.foreach(Option.scala:407)
	at io.smartdatalake.workflow.action.Action.postExec(Action.scala:158)
	at io.smartdatalake.workflow.action.Action.postExec$(Action.scala:156)
	at io.smartdatalake.workflow.action.SparkAction.postExec(SparkAction.scala:304)
	at io.smartdatalake.workflow.action.SparkSubFeedsAction.postExec(SparkSubFeedsAction.scala:169)
	at io.smartdatalake.workflow.ActionDAGRun.$anonfun$exec$2(ActionDAGRun.scala:150)
	at io.smartdatalake.workflow.DAG.$anonfun$computeNodeOperationResult$2(DAG.scala:151)
	at scala.util.Try$.apply(Try.scala:213)
	at io.smartdatalake.workflow.DAG.computeNodeOperationResult(DAG.scala:151)
	... 25 more
```
