### ISSUE TITLE
SparkStageMetricsListener UnsupportedTemporalTypeException: Unsupported field: Year

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#309]
**Describe the bug**
Running SDL 2.0.3 locally the following ERROR was reported:

```2021-01-29T16:03:24.290 level=ERROR logger=org.apache.spark.scheduler.AsyncEventQueue msg="Listener SparkStageMetricsListener threw an exception" thread="spark-listener-group-shared"
java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: Year
            at java.time.Instant.getLong(Instant.java:602) ~[?:?]
            at java.time.format.DateTimePrintContext$1.getLong(DateTimePrintContext.java:205) ~[?:?]
            at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:308) ~[?:?]
            at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2702) ~[?:?]
            at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2341) ~[?:?]
            at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2341) ~[?:?]
            at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2341) ~[?:?]
            at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1843) ~[?:?]
            at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1817) ~[?:?]
            at io.smartdatalake.metrics.SparkStageMetrics.getAsText(SparkStageMetrics.scala:86) ~[sdl-core_2.12-2.0.3-1-20210127.072301-1.jar:2.0.3-1-SNAPSHOT]
            at io.smartdatalake.workflow.action.Action.onRuntimeMetrics(Action.scala:269) ~[sdl-core_2.12-2.0.3-1-20210127.072301-1.jar:2.0.3-1-SNAPSHOT]
            at io.smartdatalake.workflow.action.Action.onRuntimeMetrics$(Action.scala:259) ~[sdl-core_2.12-2.0.3-1-20210127.072301-1.jar:2.0.3-1-SNAPSHOT]
            at io.smartdatalake.workflow.action.SparkAction.onRuntimeMetrics(SparkAction.scala:36) ~[sdl-core_2.12-2.0.3-1-20210127.072301-1.jar:2.0.3-1-SNAPSHOT]
            at io.smartdatalake.workflow.ActionDAGRun.notifyActionMetric(ActionDAGRun.scala:249) ~[sdl-core_2.12-2.0.3-1-20210127.072301-1.jar:2.0.3-1-SNAPSHOT]
            at io.smartdatalake.workflow.ActionDAGRun.$anonfun$exec$1(ActionDAGRun.scala:139) ~[sdl-core_2.12-2.0.3-1-20210127.072301-1.jar:2.0.3-1-SNAPSHOT]
            at io.smartdatalake.workflow.ActionDAGRun.$anonfun$exec$1$adapted(ActionDAGRun.scala:139) ~[sdl-core_2.12-2.0.3-1-20210127.072301-1.jar:2.0.3-1-SNAPSHOT]
            at io.smartdatalake.metrics.SparkStageMetricsListener.onStageCompleted(SparkStageMetrics.scala:188) ~[sdl-core_2.12-2.0.3-1-20210127.072301-1.jar:2.0.3-1-SNAPSHOT]
            at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:35) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:115) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:99) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.12.jar:?]
            at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.12.jar:?]
            at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1319) [spark-core_2.12-3.0.1.jar:3.0.1]
            at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.0.1.jar:3.0.1]
```

**To Reproduce**
DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(Instant.ofEpochMilli( 100L))

**Expected behavior**
Parsing a long value into a date doesnt seem to be safe in SparkStageMetrics.getAsText(SparkStageMetrics.scala:86). Errors should be catched and the original value with Remark "could not parse" written in getAsText.

**Comment by zzeekk** [comment]
Fix is to add timezone to formatter:
DateTimeFormatter.ISO_OFFSET_DATE_TIME.withZone(ZoneId.systemDefault).format(Instant.ofEpochMilli( 100L))
