### ISSUE TITLE
FileIncrementalMoveMode throws Exception for HDFS-HDFS Copy Action

### ISSUE THREAD

**Issue by burriad** [smart-data-lake/smart-data-lake#521]
Expected Behavior: CopyAction can be configured with executionMode 'FileIncrementalMoveMode' in order to move files on HDFS without deleting the source directory as well

Actual Behavior: Exception (see below)

Config-File:
https://code.sbb.ch/projects/TP_TMS_ANALYTICS/repos/efa-sdp-extract-adl/browse/src/dist/conf/corridor-conflict.conf?at=refs%2Fheads%2Ffeature%2Ffileincrementalmovemode

SDL-Version: 1.3.2

Stacktrace:
2022-05-09 07:49:12 INFO  SparkContext:54 - Invoking stop() from shutdown hook
Exception in thread "main" io.smartdatalake.util.dag.TaskFailedException: Task backup-corridor-conflict-action failed. Root cause is 'ConfigurationException: (Action~backup-corridor-conflict-action) FileIncrementalMoveMode needs FileRefDataObject and FileSubFeed as input'
Caused by: io.smartdatalake.config.ConfigurationException: (Action~backup-corridor-conflict-action) FileIncrementalMoveMode needs FileRefDataObject and FileSubFeed as input
	at io.smartdatalake.definitions.FileIncrementalMoveMode.apply(ExecutionMode.scala:466)
	at io.smartdatalake.workflow.action.Action$$anonfun$applyExecutionMode$1$$anonfun$apply$7.apply(Action.scala:212)
	at io.smartdatalake.workflow.action.Action$$anonfun$applyExecutionMode$1$$anonfun$apply$7.apply(Action.scala:212)
	at scala.Option.flatMap(Option.scala:171)
	at io.smartdatalake.workflow.action.Action$$anonfun$applyExecutionMode$1.apply(Action.scala:212)
	at io.smartdatalake.workflow.action.Action$$anonfun$applyExecutionMode$1.apply(Action.scala:212)
	at scala.util.Try$.apply(Try.scala:192)
	at io.smartdatalake.workflow.action.Action$class.applyExecutionMode(Action.scala:211)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.applyExecutionMode(ActionSubFeedsImpl.scala:39)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.prepareInputSubFeeds(ActionSubFeedsImpl.scala:90)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.init(ActionSubFeedsImpl.scala:155)
	at io.smartdatalake.workflow.ActionDAGRun$$anonfun$7.apply(ActionDAGRun.scala:128)
	at io.smartdatalake.workflow.ActionDAGRun$$anonfun$7.apply(ActionDAGRun.scala:119)
	at io.smartdatalake.util.dag.DAG$$anonfun$7.apply(DAG.scala:152)
	at io.smartdatalake.util.dag.DAG$$anonfun$7.apply(DAG.scala:152)
	at scala.util.Try$.apply(Try.scala:192)
	at io.smartdatalake.util.dag.DAG.io$smartdatalake$util$dag$DAG$$computeNodeOperationResult(DAG.scala:152)
	at io.smartdatalake.util.dag.DAG$$anonfun$3$$anonfun$4.apply(DAG.scala:131)
	at io.smartdatalake.util.dag.DAG$$anonfun$3$$anonfun$4.apply(DAG.scala:121)

**Comment by zzeekk** [comment]
Hi @burriad, you are using CopyAction with FileIncrementalMoveMode. CopyAction works with DataFrameSubFeed and not FileSubFeed. You need to use FileTransferAction to use FileIncrementalMoveMode, but i dont know if this fits your use case.

Note: in SDLB 2.x Version im currently working on #517 and #519 to implement incremental modes for DataFrameSubFeed with SparkFileDataObjects .
