### ISSUE TITLE
ClassCastException: class io.smartdatalake.util.secrets.StringOrSecret

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#726]
**Describe the bug**
With SDL 2.5.1 the application throws a `ClassCastException`:
```
Exception in thread "main" java.lang.ClassCastException: class io.smartdatalake.util.secrets.StringOrSecret cannot be cast to class java.lang.String (io.smartdatalake.util.secrets.StringOrSecret is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at io.smartdatalake.OracleStatusTracker.dataObject$lzycompute(OracleStatusTracker.scala:27)
        at io.smartdatalake.OracleStatusTracker.dataObject(OracleStatusTracker.scala:27)
        at io.smartdatalake.OracleStatusTracker.init(OracleStatusTracker.scala:40)
        at io.smartdatalake.workflow.ActionDAGRun.$anonfun$init$1(ActionDAGRun.scala:131)
        at io.smartdatalake.workflow.ActionDAGRun.$anonfun$init$1$adapted(ActionDAGRun.scala:131)
        at scala.collection.Iterator.foreach(Iterator.scala:943)
        at scala.collection.Iterator.foreach$(Iterator.scala:943)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at io.smartdatalake.workflow.ActionDAGRun.init(ActionDAGRun.scala:131)
        at io.smartdatalake.app.SmartDataLakeBuilder.exec(SmartDataLakeBuilder.scala:518)
        at io.smartdatalake.app.SmartDataLakeBuilder.startRun(SmartDataLakeBuilder.scala:477)
        at io.smartdatalake.app.SmartDataLakeBuilder.run(SmartDataLakeBuilder.scala:343)
        at io.smartdatalake.app.DefaultSmartDataLakeBuilder.parseAndRun(DefaultSmartDataLakeBuilder.scala:38)
        at io.smartdatalake.app.DefaultSmartDataLakeBuilder$.main(DefaultSmartDataLakeBuilder.scala:56)
        at io.smartdatalake.app.DefaultSmartDataLakeBuilder.main(DefaultSmartDataLakeBuilder.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:958)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

With the former version 2.4.2 this worked. Maybe we must adjust some configuration?

**To Reproduce**
Configuration:
```yaml
      mvr-process-market_abuses_insider1 {
        type = CustomDataFrameAction
        inputIds = [market_abuses_insider1_enriched]
        outputIds = [crmpf_store_case_request, market_abuses_insider1_processed]
        transformer {
          className = ch.postfinance.oi.cpl.mvr.ProcessInsider1Transformer
          options = {
            fileType = market_abuses_insider1
          }
        }
        // prevent wrong usage
        executionMode.type = FailIfNoPartitionValuesMode
        metadata {
          feed = mvr-market_abuses_insider1-spark
        }
      }

      oi-cpl-ora {
        type = JdbcTableConnection
        driver = "oracle.jdbc.OracleDriver"
        authMode = {
          type = BasicAuthMode
          userVariable = ${cpl-db.user}
          passwordVariable = ${cpl-db.password}
        }
        url = ${cpl-db.url}
        db = ${cpl-db.schema}
        autoCommit = false
      }

      status {
        type = JdbcTableDataObject
        connectionId = oi-cpl-ora
        table = {
          name = "~{id}"
        }
      }

      stateListeners = [{
        className = io.smartdatalake.OracleStatusTracker
        options = {
          dataObjectId = status
        }
      }]

```

**Expected behavior**
No exception is thrown

**Additional context**
-

**Comment by zzeekk** [comment]
Hi @AdiWehrli,

With 2.5.0 we made improvements to insert Secrets more generally in the configuration, see also documentation
http://smartdatalake.ch/docs/reference/hoconSecrets

The "userVariable = ${cpl-db.user}" and "passwordVariable = ${cpl-db.password}" are actually deprecated (but should still work), you should use "user" and "password" for future versions (see also https://smartdatalake.ch/JsonSchemaViewer/?schema=sdl-schema-2.5.1.json&path=%5B1%2C3%2C3%2C1%2C1%5D).

The problem in your case is probably that your OracleStatusTracker class reads options from the StateListenerConfig (https://smartdatalake.ch/JsonSchemaViewer/?schema=sdl-schema-2.5.1.json&path=%5B0%2C6%2C0%2C1%5D), which before were just a string, but are now a StringOrSecret object. To get the actual string you need to call .resolve() on it.

**Comment by AdiWehrli** [comment]
The problem was, that `OracleStatusTracker` was still using `OracleStatusTracker(options: Map[String,String])` instead of `OracleStatusTracker(options: Map[String,StringOrSecret])`.
