### ISSUE TITLE
Empty DataObject leads to NoMetricsReceivedException 

### ISSUE THREAD

**Issue by PMuellerELCA** [smart-data-lake/smart-data-lake#874]
When an action does not process any records because the source is empty, this action throws a NoMetricsReceivedException stating that it "did not receive metrics within timeout of 10 seconds".

Solution: This should not be a problem. The action should just exit and move on.

Here is a stack trace for this case:
Caused by: io.smartdatalake.workflow.dataframe.spark.NoMetricsReceivedException: SparkObservation DataObject~brz-annotations-transcripts-fb4ec3d4-469c-4be0-8b7b-85992714e275 did not receive metrics within timeout of 10 seconds.
	at io.smartdatalake.workflow.dataframe.spark.SparkObservation.waitFor(SparkObservation.scala:68)
	at io.smartdatalake.workflow.action.DataFrameActionImpl.$anonfun$writeSubFeed$3(DataFrameActionImpl.scala:285)
	at scala.Option.map(Option.scala:230)
	at io.smartdatalake.workflow.action.DataFrameActionImpl.writeSubFeed(DataFrameActionImpl.scala:285)
	at io.smartdatalake.workflow.action.DataFrameActionImpl.writeSubFeed(DataFrameActionImpl.scala:47)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.$anonfun$writeOutputSubFeeds$5(ActionSubFeedsImpl.scala:158)
	at io.smartdatalake.util.misc.PerformanceUtils$.measureDuration(PerformanceUtils.scala:48)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.$anonfun$writeOutputSubFeeds$1(ActionSubFeedsImpl.scala:158)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.writeOutputSubFeeds(ActionSubFeedsImpl.scala:149)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.exec(ActionSubFeedsImpl.scala:216)
	at io.smartdatalake.workflow.ActionDAGRun.$anonfun$exec$1(ActionDAGRun.scala:179)
	at scala.Function2.$anonfun$tupled$1(Function2.scala:53)
	at io.smartdatalake.workflow.ActionDAGRun.$anonfun$run$1(ActionDAGRun.scala:79)
	at io.smartdatalake.util.dag.DAG.$anonfun$computeNodeOperationResult$2(DAG.scala:152)
	at scala.util.Try$.apply(Try.scala:213)
	at io.smartdatalake.util.dag.DAG.computeNodeOperationResult(DAG.scala:152)
	at io.smartdatalake.util.dag.DAG.$anonfun$buildTaskGraph$2(DAG.scala:131)

Here is the definition of the action:
  brz-annotations-transcripts {
    type = CopyAction
    inputId = irn-annotations-transcripts
    outputId = brz-annotations-transcripts
    executionMode = { type = DataObjectStateIncrementalMode }
    transformer {
      sqlCode = """
SELECT
*
FROM %{inputViewName_irn-annotations-transcripts} a
QUALIFY ROW_NUMBER() OVER(PARTITION BY a.annotationid ORDER BY a.sdlb_created_on DESC) = 1"""
    }
  }

**Comment by zzeekk** [comment]
Hi @PMuellerELCA , what SDLB version did you use?

**Comment by PMuellerELCA** [comment]
Hi. I used 2.7.0-839-SNAPSHOT.

**Comment by zzeekk** [comment]
There has been a major refactoring of this with #782, which got merged to 2.7.0 after #839 und is now available in the new release. Could you test again with the latest release?

**Comment by PMuellerELCA** [comment]
Problem resolved in version 2.7.1
