### ISSUE TITLE
Count and TransferRate expectations broken

### ISSUE THREAD

**Issue by PMuellerELCA** [smart-data-lake/smart-data-lake#896]
When adding the CountExpectation to a DeltaLakeTableDataObject or the new TransferRateExpectation to an action the program aborts with the following error message:

SDLB Version 2.7.1

```
TaskFailedException: Task slv-dim-dates failed. Root cause is 'IllegalStateException: (DataObject~slv-dim-dates) Metric 'countXXX' for expectation 'countXXX' not found for validation'
Caused by: IllegalStateException: (DataObject~slv-dim-dates) Metric 'countXXX' for expectation 'countXXX' not found for validation
Caused by: java.lang.IllegalStateException: (DataObject~slv-dim-dates) Metric 'countXXX' for expectation 'countXXX' not found for validation
	at io.smartdatalake.workflow.dataobject.expectation.BaseExpectation.$anonfun$getMetric$1(Expectation.scala:89)
	at scala.collection.immutable.Map$Map2.getOrElse(Map.scala:236)
	at io.smartdatalake.workflow.dataobject.expectation.BaseExpectation.getMetric(Expectation.scala:89)
	at io.smartdatalake.workflow.dataobject.expectation.BaseExpectation.getMetric$(Expectation.scala:87)
	at io.smartdatalake.workflow.dataobject.expectation.CountExpectation.getMetric(CountExpectation.scala:44)
	at io.smartdatalake.workflow.dataobject.expectation.CountExpectation.getValidationErrorColumn(CountExpectation.scala:81)
	at io.smartdatalake.workflow.dataobject.ExpectationValidation.$anonfun$validateExpectations$3(ExpectationValidation.scala:168)
	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
	at io.smartdatalake.workflow.dataobject.ExpectationValidation.validateExpectations(ExpectationValidation.scala:166)
	at io.smartdatalake.workflow.dataobject.ExpectationValidation.validateExpectations$(ExpectationValidation.scala:152)
	at io.smartdatalake.workflow.dataobject.DeltaLakeTableDataObject.validateExpectations(DeltaLakeTableDataObject.scala:102)
	at io.smartdatalake.workflow.action.DataFrameActionImpl.writeSubFeed(DataFrameActionImpl.scala:349)
	at io.smartdatalake.workflow.action.DataFrameActionImpl.writeSubFeed(DataFrameActionImpl.scala:47)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.$anonfun$writeOutputSubFeeds$5(ActionSubFeedsImpl.scala:160)
	at io.smartdatalake.util.misc.PerformanceUtils$.measureDuration(PerformanceUtils.scala:48)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.$anonfun$writeOutputSubFeeds$1(ActionSubFeedsImpl.scala:160)
        more....
```

```
TaskFailedException: Task slv-dim-queues failed. Root cause is 'IllegalStateException: (DataObject~slv-dim-queues) Metric 'count' for expectation 'pctTransfer' not found for validation'
Caused by: IllegalStateException: (DataObject~slv-dim-queues) Metric 'count' for expectation 'pctTransfer' not found for validation
Caused by: java.lang.IllegalStateException: (DataObject~slv-dim-queues) Metric 'count' for expectation 'pctTransfer' not found for validation
	at io.smartdatalake.workflow.dataobject.expectation.BaseExpectation.$anonfun$getMetric$1(Expectation.scala:89)
	at scala.collection.immutable.HashMap$HashTrieMap.getOrElse0(HashMap.scala:596)
	at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:73)
	at io.smartdatalake.workflow.dataobject.expectation.BaseExpectation.getMetric(Expectation.scala:89)
	at io.smartdatalake.workflow.dataobject.expectation.BaseExpectation.getMetric$(Expectation.scala:87)
	at io.smartdatalake.workflow.action.expectation.TransferRateExpectation.getMetric(TransferRateExpectation.scala:43)
	at io.smartdatalake.workflow.action.expectation.TransferRateExpectation.getValidationErrorColumn(TransferRateExpectation.scala:56)
	at io.smartdatalake.workflow.dataobject.ExpectationValidation.$anonfun$validateExpectations$3(ExpectationValidation.scala:168)
        more...
```

Configuration for the count expectation:
```
dataObjects {
    slv-dim-dates {
        type = DeltaLakeTableDataObject
        saveMode = Overwrite
        expectations = [{type = CountExpectation, name = "countXXX"}]
        table {
            catalog = ${env.catalog_name}
            db = ${env.slv_schema}
            name = "dim_dates"
            primaryKey = ["date_id"]
        }
    }
}
```

Configuration for the transfer rate:
```
actions { 
    slv-dim-queues {
        type = CustomDataFrameAction
        inputIds = [brz-queues, slv-dim-users, slv-dim-users-mapping]
        outputIds = [slv-dim-queues]
        executionMode = { type = ProcessAllMode }
        mainInputId = brz-queues
        expectations = [{type = TransferRateExpectation}]
		transformer {
                   ...
```

**Comment by zzeekk** [comment]
Tested ok.
