### ISSUE TITLE
DeduplicateAction should support a Schema Change between InputDO and OutputDO

### ISSUE THREAD

**Issue by Geheiner** [smart-data-lake/smart-data-lake#903]
**Describe the bug**
Currently, DeduplicateAction is not working if you have transformations that modify the schema. If the schema of the inputDO is not the same as the outputDO, you will get an error similar to this:
**To Reproduce**

Use this simplified conf File and upload it into a folder called data in your working directory  (you can remove .txt ending that was just added to make github happy):

``
[departues.conf.txt](https://github.com/user-attachments/files/17521036/departues.conf.txt)

And use this data as sample Input:
[part-00000-b75ac798-642b-446c-8de9-1274576e4c13-c000.csv](https://github.com/user-attachments/files/17520962/part-00000-b75ac798-642b-446c-8de9-1274576e4c13-c000.csv)

Run it using this intelliJ run config (you can remove .txt ending that was just added to make github happy)
[SDLB_download_departures.xml.txt](https://github.com/user-attachments/files/17521074/SDLB_download_departures.xml.txt)

Run the pipeline 2 times.
It will fail on the second attempt with this error:

```
2024-10-25 13:08:49 ERROR ActionDAGRun - Exec: TaskFailedException: Task download-deduplicate-departures failed. Root cause is 'AnalysisException: [UNSUPPORTED_OVERWRITE.TABLE] Can't overwrite the target that is also being read from. The target table is `spark_catalog`.`default`.`int_departures`.' [main]
2024-10-25 13:08:49 INFO  ActionDAGRun$ - Exec FAILED for download-deduplicate-departures runId=1 attemptId=1:
                       ┌─────┐                        
                       │start│                        
                       └───┬─┘                        
                           │                          
                           v                          
 ┌───────────────────────────────────────────────────┐
 │download-deduplicate-departures FAILED PT0.8660096S│
 └───────────────────────────────────────────────────┘
 [main]
Exception in thread "main" io.smartdatalake.util.dag.TaskFailedException: Task download-deduplicate-departures failed. Root cause is 'AnalysisException: [UNSUPPORTED_OVERWRITE.TABLE] Can't overwrite the target that is also being read from. The target table is `spark_catalog`.`default`.`int_departures`.'
Caused by: org.apache.spark.sql.AnalysisException: [UNSUPPORTED_OVERWRITE.TABLE] Can't overwrite the target that is also being read from. The target table is `spark_catalog`.`default`.`int_departures`.
	at org.apache.spark.sql.errors.QueryCompilationErrors$.cannotOverwriteTableThatIsBeingReadFromError(QueryCompilationErrors.scala:2627)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:663)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:587)
	at org.apache.spark.sql.DataFrameWriter.saveAsTable(DataFrameWriter.scala:568)
	at io.smartdatalake.workflow.dataobject.DeltaLakeTableDataObject.$anonfun$writeDataFrame$8(DeltaLakeTableDataObject.scala:345)
	at io.smartdatalake.metrics.SparkStageMetricsListener$.execWithMetrics(SparkStageMetricsListener.scala:153)
	at io.smartdatalake.workflow.dataobject.DeltaLakeTableDataObject.writeDataFrame(DeltaLakeTableDataObject.scala:329)
	at io.smartdatalake.workflow.dataobject.DeltaLakeTableDataObject.writeSparkDataFrame(DeltaLakeTableDataObject.scala:296)
	at io.smartdatalake.workflow.dataobject.CanWriteSparkDataFrame.writeDataFrame(CanWriteSparkDataFrame.scala:53)
	at io.smartdatalake.workflow.dataobject.CanWriteSparkDataFrame.writeDataFrame$(CanWriteSparkDataFrame.scala:51)
	at io.smartdatalake.workflow.dataobject.DeltaLakeTableDataObject.writeDataFrame(DeltaLakeTableDataObject.scala:102)
	at io.smartdatalake.workflow.action.DataFrameActionImpl.writeSubFeed(DataFrameActionImpl.scala:469)
	at io.smartdatalake.workflow.action.DataFrameActionImpl.writeSubFeed(DataFrameActionImpl.scala:334)
	at io.smartdatalake.workflow.action.DataFrameActionImpl.writeSubFeed(DataFrameActionImpl.scala:47)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.$anonfun$writeOutputSubFeeds$5(ActionSubFeedsImpl.scala:160)
	at io.smartdatalake.util.misc.PerformanceUtils$.measureDuration(PerformanceUtils.scala:48)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.$anonfun$writeOutputSubFeeds$1(ActionSubFeedsImpl.scala:160)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.writeOutputSubFeeds(ActionSubFeedsImpl.scala:150)
	at io.smartdatalake.workflow.action.ActionSubFeedsImpl.exec(ActionSubFeedsImpl.scala:234)
	at io.smartdatalake.workflow.ActionDAGRun.$anonfun$exec$1(ActionDAGRun.scala:178)
	at scala.Function2.$anonfun$tupled$1(Function2.scala:53)
	at io.smartdatalake.workflow.ActionDAGRun.$anonfun$run$1(ActionDAGRun.scala:78)
	at io.smartdatalake.util.dag.DAG.$anonfun$computeNodeOperationResult$2(DAG.scala:152)
	at scala.util.Try$.apply(Try.scala:213)
	at io.smartdatalake.util.dag.DAG.computeNodeOperationResult(DAG.scala:152)
	at io.smartdatalake.util.dag.DAG.$anonfun$buildTaskGraph$2(DAG.scala:131)

```

**Expected behavior**
You can change the schema of your Output when using DeduplicateAction 

**Additional context**

The problem of DeduplicateAction is located here: https://github.com/smart-data-lake/smart-data-lake/blob/master-spark3/sdl-core/src/main/scala/io/smartdatalake/workflow/action/DeduplicateAction.scala#L165

We are comparing source and target schema of the whole action, but we should be comparing source and target schema of the dataframes of the last transformer of this action

**Comment by zzeekk** [comment]
> Caused by: org.apache.spark.sql.AnalysisException: [UNSUPPORTED_OVERWRITE.TABLE] Can't overwrite the target that is also being read from. The target table is `spark_catalog`.`default`.`int_departures`.
	at org.apache.spark.sql.errors.QueryCompilationErrors$.cannotOverwriteTableThatIsBeingReadFromError(QueryCompilationErrors.scala:2627)

This problem is solved by setting `mergeModeEnabled=true`.

But there is another problem because `StandardizeColNamesTransformer` will change also the name of the primaryKey column `estArrivalAirport` to `est_departure_airport`. This is solved through adapting the primaryKey in int-departures.table.primaryKey.

Now there is another probleme because of renaming of the primaryKey: The primaryKey columns are not present in the existing table (created by a previous run). Currently the merge statement will fail with a message that it doesn't find column `est_departure_airport`. I will improve that. The existance of the primaryKey columns in an existing table should be validated already in prepare phase.

Otherwise, changing a column name in a transformer of DeduplicateAction 2.8.0-SNAPSHOT (branch feature/916-generic-deduplicate-historize) works in initial and 2nd run. I will add corresponding tests.

**Comment by Geheiner** [comment]
what's the status @zzeekk ?  You added some commits and then assigned me, should I review something?
![pulp-fiction-wtf](https://github.com/user-attachments/assets/f72b5ead-50a2-4faf-8c92-541df0df5b87)

**Comment by zzeekk** [comment]
> Otherwise, changing a column name in a transformer of DeduplicateAction 2.8.0-SNAPSHOT (branch feature/916-generic-deduplicate-historize) works in initial and 2nd run. I will add corresponding tests.

@Geheiner can you verify that it works as well for you? (I have added tests...)

**Comment by Geheiner** [comment]
ah and it s already on develop-spark-3 and not on your branch anymore right?

**Comment by zzeekk** [comment]
Yes :-)

**Comment by Geheiner** [comment]
Hi, it looks good to me, I can no longer reproduce my problem after your changes. Hell, with this change I even saw an error in my example because the input data set itself is duplicated, something that DEDUPLICATEAction is not built to handle out of the box.
This made me go into a little rabbit whole about slowly changing dimensions.
For me, DeduplicateAction is actually our implementation of SDC Type 1 and HistorizeAction is SDC Type 2.
Given that I'm not the only one who constantly has to think about what DeduplicateAction means, maybe we can start 2025 with a little discussion about renaming that Action to SDCType1Action... And setting mergeModeEnable to true by default and throwing an error if the outputDO does not support it?

Anyways, your change seams good, I may add a cosmetical commit later

**Comment by Geheiner** [comment]
Actually, I have nothing to add, I now understand your tests and they make sense to me, I'm closing the issue.
